//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatement
    {
        public int StatementID { get; set; }
        public int AccountID { get; set; }
        public int StatementMonth { get; set; }
        public int StatementYear { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> TotalDeposits { get; set; }
        public Nullable<int> TransactionCount { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
