//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string RequestType { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public string StopPaymentReason { get; set; }
        public string NewAddress { get; set; }
        public string NewCity { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
